### ISSUE TITLE
how to user paginator?

### ISSUE THREAD

**Issue by cnphar** [brainlabs/ci-eloquent#1]
when I user on controller:

$this->load->model('name_of_class'); // name_of_class is model extend ORM

$data['a'] = $this->name_of_class->where('id','>',0)->paginate(2); // Error

error info:
Fatal error: Uncaught exception 'ReflectionException' with message 'Class paginator does not exist' in D:\wamp\www\ci-eloquent-master\vendor\illuminate\container\Illuminate\Container\Container.php on line 504

How to overcome it and use eloquent an paginator in CI?

Thx

**Comment by brainlabs** [comment]
for advance please read documentation  eloquent of laravel, thanks before

**Comment by cnphar** [comment]
thx
